services:
  # Web Server
  web:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    volumes:
      - "../src/:/var/www/html/"
    ports:
      - "8081:80"

  # MySQL Database
  server-mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - mysql-data:/var/lib/mysql
    
  # Optional MySQL Management Tool
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: server-mysql
      PMA_USER: root
      PMA_PASSWORD: mypassword
    ports:
      - "3333:80"
volumes:
  mysql-data:
